use std::path::PathBuf;

use ts_rs::{Config, TS};

use super::*;

#[test]
fn export_console_types() {
    let output = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../console/src/generated");
    if output.exists() {
        std::fs::remove_dir_all(&output).expect("clear generated TypeScript");
    }
    std::fs::create_dir_all(&output).expect("create generated TypeScript directory");
    let config = Config::new().with_out_dir(&output).with_large_int("number");
    macro_rules! export {
        ($($ty:ty),+ $(,)?) => {$({
            <$ty>::export_all(&config).expect(concat!("export ", stringify!($ty)));
        })+};
    }
    export!(
        crate::route::Entity,
        AdminIdentityDto,
        SessionStatusDto,
        SetupRequest,
        LoginRequest,
        AuthResponse,
        OAuthClientDto,
        OAuthClientWriteRequest,
        OAuthSessionDto,
        OAuthSessionPageDto,
        OAuthAuthorizationRequest,
        OAuthConsentDto,
        OAuthAuthorizeDecision,
        OAuthRedirectDto,
        OAuthDeviceDecision,
        OAuthErrorDto,
        IdResponse,
        AppliedResponse,
        AutostartStatusDto,
        AutostartUpdateRequest,
        UpdateStatusDto,
        UpdateAppliedDto,
        BatchActionDto,
        BatchRequest,
        BatchItemOutcome,
        BatchResponse,
        SecretExportDto,
        ExportSourceKeyDto,
        CredentialEnvelopeDto,
        ExportCredentialDto,
        ExportUserKeyDto,
        ConfigurationDataDto,
        ConfigurationExportDto,
        ConfigurationExportRequest,
        ConfigurationImportRequest,
        ConfigurationImportResponse,
        ConnectivityScopeDto,
        ConnectivityTestRequest,
        ConnectivityProxySourceDto,
        ConnectivityProbeDto,
        ConnectivityTestResponse,
        ErrorEnvelope,
        ChannelSupportDto,
        ChannelDto,
        ChannelFieldControlDto,
        ChannelFieldDto,
        TrafficPolicyDto,
        TrafficBlacklistDto,
        LoginModeDto,
        LoginParamKindDto,
        LoginParamConditionDto,
        LoginParamDto,
        ChannelLoginDto,
        AuthCodeStartRequest,
        AuthCodeStartResponse,
        AuthCodeCompleteRequest,
        DeviceStartRequest,
        DeviceStartResponse,
        DevicePollRequest,
        DevicePollResponse,
        CookieExchangeRequest,
        TlsPresetDto,
        AlpnDto,
        TlsVersionDto,
        PseudoHeaderDto,
        TlsProfileDto,
        Http2ProfileDto,
        TlsFingerprintDto,
        ProviderDto,
        ProviderWriteRequest,
        CredentialHealthDto,
        CredentialDto,
        QuotaCapabilitiesDto,
        CycleEstimateDto,
        CycleObservationDto,
        CredentialCycleReadRequest,
        CredentialWriteRequest,
        CredentialSecretResponse,
        RouteDto,
        RouteWriteRequest,
        RouteMemberDto,
        RouteMemberWriteRequest,
        AliasDto,
        AliasWriteRequest,
        ModelAliasDto,
        ModelDiscoverRequest,
        ModelDiscoverResponse,
        ModelTestRequest,
        ModelTestResponse,
        QuotaProbeResponse,
        gproxy_channel_api::QuotaSnapshot,
        QuotaProbeWindowDto,
        QuotaResetCreditsDto,
        QuotaResetOutcomeDto,
        QuotaResetResponse,
        ProviderModelDto,
        ProviderModelWriteRequest,
        ModelAliasWriteRequest,
        RoutingImplementationDto,
        RoutingRuleDto,
        RoutingRuleWriteRequest,
        RuleSetDto,
        RuleSetWriteRequest,
        TextPositionDto,
        RewriteActionDto,
        HeaderModeDto,
        TransformPhaseDto,
        TransformLocateDto,
        TransformActionDto,
        RuleConfigDto,
        RuleDto,
        RuleWriteRequest,
        ProviderRuleSetDto,
        ProviderRuleSetWriteRequest,
        RulePresetCategoryDto,
        RulePresetRuleDto,
        RulePresetDto,
        PriceRuleDto,
        PriceRuleWriteRequest,
        PriceRateDto,
        PriceRateWriteRequest,
        PriceCatalogDto,
        PriceProfileDto,
        PriceProfileKindDto,
        PriceMetricDto,
        DefaultModelCatalogDto,
        DefaultModelCatalogSourceDto,
        DefaultModelDto,
        DefaultModelPricingDto,
        DefaultModelPriceRateDto,
        ApplyDefaultModelPricesRequest,
        ApplyDefaultModelPricesResponse,
        OrganizationDto,
        OrganizationWriteRequest,
        TeamDto,
        TeamWriteRequest,
        UserDto,
        UserWriteRequest,
        UserPasswordRequest,
        UserKeyPrefix,
        UserKeyDto,
        UserKeyCreateRequest,
        UserKeyUpdateRequest,
        UserKeyCreateResponse,
        UserKeyRevealResponse,
        PermissionDto,
        PermissionWriteRequest,
        RateLimitDto,
        RateLimitWriteRequest,
        QuotaDto,
        QuotaWriteRequest,
        UsageGroupByDto,
        UsageQueryDto,
        UsageRecordQueryDto,
        UsageRecordDto,
        UsageRecordPageDto,
        UsageSummaryDto,
        UsageStatisticsDto,
        UsageTrendQueryDto,
        UsageTrendPointDto,
        QuotaWindowDto,
        BoundarySourceDto,
        BoundaryConfidenceDto,
        QuotaCoverageDto,
        QuotaCycleStatusDto,
        QuotaCycleCloseReasonDto,
        CredentialQuotaCycleDto,
        LogQueryDto,
        LogListItemDto,
        LogPageDto,
        DownstreamLogDto,
        WireLogDto,
        LogDetailDto,
        LogSettingsDto,
        LogSettingsUpdateDto,
        UpdateChannelDto,
        InstanceSettingsDto,
        TokenizerVocabDto,
        TokenizerFetchRequest,
        TokenizerDeleteRequest,
        TokenizerDownloadProgressDto,
        TokenizerAuthDto,
        TokenizerAuthUpdate,
        TokenizerAuthRevealResponse,
        AuditEventDto,
        PortalContextDto,
        PortalLoginRequest,
        PortalSessionStatusDto,
        PortalPasswordChangeRequest,
        PortalKeyCreateRequest,
        PortalSettingsDto,
        PortalModelCapabilityDto,
        PortalModelDto,
        PortalUsageQueryDto,
        PortalUsageDto,
        PortalQuotaScopeDto,
        PortalQuotaWindowKindDto,
        PortalQuotaWindowDto,
        PortalRecentQueryDto,
        PortalRecentRequestDto,
    );
    let mut names = std::fs::read_dir(&output)
        .expect("read generated TypeScript")
        .map(|entry| entry.expect("generated entry").file_name())
        .filter_map(|name| name.into_string().ok())
        .filter_map(|name| name.strip_suffix(".ts").map(str::to_owned))
        .filter(|name| name != "index")
        .collect::<Vec<_>>();
    names.sort();
    let index = names
        .into_iter()
        .map(|name| format!("export * from \"./{name}\";\n"))
        .collect::<String>();
    std::fs::write(output.join("index.ts"), index).expect("write generated TypeScript index");
}
